### DISCUSSION TITLE
Ero 403 (Forbidden) ao fazer o deploy

### DISCUSSION THREAD

**Discussion by under-sin** [balta-io/forum#346] [Tira Dúvidas] [answered]
Bom, eu já vi todas as publicações relacionadas a esse erro, a que falava de duplicação e tudo mais. 
Ainda continue com esse erro. Alguém tem alguma solução que possa me ajuda?

![image](https://github.com/balta-io/forum/assets/61955074/27bf2667-67b4-4cc2-9fc6-3edb076e7bc3)

```yml
name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Create the pack
        run: dotnet pack --configuration Release

      - name: Publish
        run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/under-sin/index.json --skip-duplicate

```
